<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    BaksDev\Core\BaksDevCoreBundle::class => ['all' => true],
    BaksDev\Captcha\BaksDevCaptchaBundle::class => ['all' => true],
    BaksDev\Auth\Email\BaksDevAuthEmailBundle::class => ['all' => true],
    BaksDev\Field\Pack\BaksDevFieldPackBundle::class => ['all' => true],
    BaksDev\Files\Cdn\BaksDevFilesCdnBundle::class => ['all' => true],
    BaksDev\Files\Resources\BaksDevFilesResourcesBundle::class => ['all' => true],
    BaksDev\Reference\Color\BaksDevReferenceColorBundle::class => ['all' => true],
    BaksDev\Reference\Gender\BaksDevReferenceGenderBundle::class => ['all' => true],
    BaksDev\Settings\Main\BaksDevSettingsMainBundle::class => ['all' => true],
    BaksDev\Users\Profile\Group\BaksDevUsersProfileGroupBundle::class => ['all' => true],
    BaksDev\Users\Profile\TypeProfile\BaksDevUsersProfileTypeProfileBundle::class => ['all' => true],
    BaksDev\Users\Profile\UserProfile\BaksDevUsersProfileUserProfileBundle::class => ['all' => true],
    BaksDev\Users\User\BaksDevUsersUserBundle::class => ['all' => true],
    BaksDev\Products\Product\BaksDevProductsProductBundle::class => ['all' => true],
    BaksDev\Products\Category\BaksDevProductsCategoryBundle::class => ['all' => true],
    BaksDev\Products\Viewed\BaksDevProductsViewedBundle::class => ['all' => true],
    BaksDev\Menu\Admin\BaksDevMenuAdminBundle::class => ['all' => true],
    BaksDev\Payment\BaksDevPaymentBundle::class => ['all' => true],
    BaksDev\Delivery\BaksDevDeliveryBundle::class => ['all' => true],
    BaksDev\DeliveryTransport\BaksDevDeliveryTransportBundle::class => ['all' => true],
    BaksDev\Contacts\Region\BaksDevContactsRegionBundle::class => ['all' => true],
    BaksDev\Reference\Region\BaksDevReferenceRegionBundle::class => ['all' => true],
    BaksDev\Orders\Order\BaksDevOrdersOrderBundle::class => ['all' => true],
    BaksDev\Products\Stocks\BaksDevProductsStocksBundle::class => ['all' => true],
    BaksDev\Users\Address\BaksDevUsersAddressBundle::class => ['all' => true],
    BaksDev\Products\Sign\BaksDevProductsSignBundle::class => ['all' => true],
    BaksDev\Products\Stocks\Telegram\BaksDevProductsStocksTelegramBundle::class => ['all' => true],
    BaksDev\Auth\Telegram\BaksDevAuthTelegramBundle::class => ['all' => true],
    BaksDev\Telegram\BaksDevTelegramBundle::class => ['all' => true],
    BaksDev\Centrifugo\BaksDevCentrifugoBundle::class => ['all' => true],
    BaksDev\Field\Country\BaksDevFieldCountryBundle::class => ['all' => true],
    BaksDev\Elastic\BaksDevElasticBundle::class => ['all' => true],
    BaksDev\Field\Tire\BaksDevFieldTireBundle::class => ['all' => true],
    BaksDev\Megamarket\BaksDevMegamarketBundle::class => ['all' => true],
    BaksDev\Megamarket\Orders\BaksDevMegamarketOrdersBundle::class => ['all' => true],
    BaksDev\Megamarket\Products\BaksDevMegamarketProductsBundle::class => ['all' => true],
    BaksDev\Reference\Money\BaksDevReferenceMoneyBundle::class => ['all' => true],
    BaksDev\Reference\Cars\BaksDevReferenceCarsBundle::class => ['all' => true],
    BaksDev\Reference\Currency\BaksDevReferenceCurrencyBundle::class => ['all' => true],
    BaksDev\Reference\Measurement\BaksDevReferenceMeasurementBundle::class => ['all' => true],
    BaksDev\Telegram\Bot\BaksDevTelegramBotBundle::class => ['all' => true],
    BaksDev\Barcode\BaksDevBarcodeBundle::class => ['all' => true],
    BaksDev\Support\BaksDevSupportBundle::class => ['all' => true],
    BaksDev\Products\Favorite\BaksDevProductsFavoriteBundle::class => ['all' => true],
    BaksDev\Search\BaksDevSearchBundle::class => ['all' => true],
];
